services:
  - type: web
    name: seo-content-generator-api
    env: docker
    buildCommand: docker build -t app .
    startCommand: ./start.sh
    healthCheckPath: /api/v1/health
    healthCheckTimeout: 100
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: seo-content-generator-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
    dependsOn:
      - seo-content-generator-db
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "https://seo-content-generator-frontend.onrender.com"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, X-Requested-With, Accept, Origin"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "86400"

  - type: web
    name: seo-content-generator-frontend
    env: static
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://seo-content-generator-jjtm.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: seo-content-generator-db
    databaseName: seo_content_db
    plan: free
