services:
  - type: web
    name: seo-content-generator-api
    env: docker
    buildCommand: docker build -t app .
    healthCheckPath: /api/v1/health
    healthCheckTimeout: 100
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: seo-content-generator-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
    dependsOn:
      - seo-content-generator-db

  - type: web
    name: seo-content-generator-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://seo-content-generator-api-jjtm.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

databases:
  - name: seo-content-generator-db
    databaseName: seo_content_db
    plan: free
