services:
  - type: web
    name: seo-content-generator
    env: docker
    buildCommand: docker build -t app .
    healthCheckPath: /api/v1/health
    healthCheckTimeout: 100
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
    dependsOn:
      - postgres

databases:
  - name: postgres
    databaseName: seo_content_db
    plan: free
