services:
  - type: web
    name: seo-content-generator
    env: docker
    buildCommand: docker build -t app .
    healthCheckPath: /api/v1/health
    healthCheckTimeout: 100
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: seo-content-generator-db
          property: connectionString

databases:
  - name: seo-content-generator-db
    databaseName: seo_content_db
    user: seo_content_user
    ipAllowList: []
